const $ = s => document.querySelector(s);
const data = {
  situations: {"Bus travel":["Choose a seat near the driver or with other passengers.","Keep your phone charged and avoid displaying valuables.","Share the bus route and expected arrival time with a trusted contact."],"Auto / Cab":["Verify the vehicle number before getting in and sit where you can exit easily.","Share vehicle details and your destination with a trusted contact.","If the route changes unexpectedly, call someone and ask the driver to stop in a public area."],"Night travel":["Prefer well-lit, familiar routes and avoid isolated pickup points.","Tell a trusted contact your expected arrival time before leaving.","Keep your phone accessible and avoid using headphones that block awareness."],"Walking alone":["Walk on well-lit roads with open shops or other people nearby.","Stay alert to your surroundings and avoid looking down at your phone.","If you feel followed, go into a public place and call for help."],"Village / unfamiliar area":["Plan your route in advance and keep a trusted contact informed.","Avoid isolated shortcuts; ask for directions in staffed public places.","Carry a charged phone and note nearby landmark names."],"Long-distance travel":["Keep ticket, vehicle and arrival details available to a trusted contact.","Stay close to populated areas at stops and keep belongings secure.","Check in at major stops or whenever your plans change."]},
  incidents:{"I feel unsafe":["Move toward a public, well-lit place with other people.","Call a trusted contact and describe where you are.","If danger is immediate, call 112."],"Unsafe travel":["Ask to stop at a safe, public location if possible.","Share the vehicle number and route details with a trusted contact.","Use 112 if you are in immediate danger."],"Being followed":["Do not go home or into an isolated place.","Enter a busy shop, station, or other public space and ask for help.","Call 112 if you believe there is an immediate threat."],"Threat / intimidation":["Move away from the person if it is safe to do so.","Avoid escalating the interaction; contact someone you trust.","Record details only if this can be done safely."],"Harassment":["Create distance and move toward people or staff.","Clearly seek help from a trusted person or authority nearby.","Preserve relevant details after you are safe."]},
  online:{"Threatening messages":["Do not engage if it could escalate the threat.","Save screenshots showing the account, date and message.","Block or report the account through the platform after preserving evidence."],"Cyberbullying":["Save the messages, usernames and dates before blocking.","Tell a trusted person; you do not need to handle it alone.","Use platform reporting tools for repeated abuse."],"Online stalking":["Review privacy settings and avoid sharing live location publicly.","Document repeated contact or unwanted messages.","Consider changing passwords and enabling two-factor authentication."],"Fake account":["Save the profile URL and screenshots of impersonation.","Ask trusted friends not to interact with the account.","Report impersonation through the platform's official process."],"Content / image misuse":["Save links, screenshots and dates of the content.","Avoid forwarding the content further.","Use the platform reporting path and seek trusted support."],"Blackmail / extortion":["Do not send money or additional material.","Preserve messages, account information and payment requests.","Tell a trusted person and seek help promptly."]}
};
let state = {screen:'home', situation:'', incident:'', online:'', journey:JSON.parse(localStorage.getItem('ssJourney')||'null'), location:localStorage.getItem('ssLocation')||'Not yet available'};
function save(){localStorage.setItem('ssJourney',JSON.stringify(state.journey));} function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function go(screen){state.screen=screen;render();window.scrollTo({top:0,behavior:'smooth'});}
function nav(){document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.go===state.screen));}
const header=(eyebrow,title,copy)=>`<div class="screen-head"><button class="back" data-go="home">← Back to home</button><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${copy}</p></div>`;
function home(){return `<section class="hero"><div class="hero-copy"><p class="eyebrow">Proactive safety companion</p><h1>Your safety,<br><em>in your hands.</em></h1><p>Practical support before, during, and after a journey or safety situation—built around the moments that matter.</p><button class="primary" data-go="safety">Plan a safer journey →</button></div><div class="hero-art"><span class="art-pill">● Safety ready</span><div class="art-title">Small steps can make a meaningful difference.</div><div class="art-person">◒</div><div class="art-note"><span>●</span> You are not alone</div></div></section><section><div class="section-title"><h2>How can we support you?</h2><p>Choose one focused path</p></div><div class="dashboard-grid"><button class="dash-card" data-go="safety"><div class="dash-icon lilac">✦</div><h3>Stay safe</h3><p>Plan a journey with practical precautions.</p></button><button class="dash-card" data-go="help"><div class="dash-icon rose">!</div><h3>I need help now</h3><p>Get immediate, situation-based guidance.</p></button><button class="dash-card" data-go="reports"><div class="dash-icon mint">▤</div><h3>Reporting</h3><p>Prepare information and evidence clearly.</p></button><button class="dash-card" data-go="online"><div class="dash-icon sand">◎</div><h3>Online harassment</h3><p>Respond safely to digital harm.</p></button></div><div class="notice"><span>✦</span><div><strong>Built for real life.</strong> SafeSphere can prepare safety information and use your browser’s location permission while it is open. Automatic messages and emergency-service integration require future authorized services.</div></div></section>`}
function safety(){let choices=Object.keys(data.situations).map((x,i)=>`<button class="choice ${state.situation===x?'selected':''}" data-situation="${x}"><span>${['◌','▱','☾','↗','⌖','⇢'][i]}</span>${x}</button>`).join('');let detail=state.situation?`<div class="panel" id="precautions"><p class="eyebrow">Before you go</p><h2>${esc(state.situation)} precautions</h2><ul class="precautions">${data.situations[state.situation].map(x=>`<li>${x}</li>`).join('')}</ul><button class="primary" data-go="setup">Start journey →</button></div>`:'';return `<section class="screen">${header('Stay safe','Plan your journey','Choose your situation first. We’ll show useful precautions before you begin.') }<div class="choice-grid">${choices}</div><div class="incident-info">${detail}</div></section>`}
function setup(){return `<section class="screen">${header('Journey setup','Where are you going?','Add the basics once. SafeSphere will save them on this device for this active journey.')}<div class="panel"><p class="step">STEP 1 OF 3 · JOURNEY DETAILS</p><form id="journey-form" class="form-grid"><label class="form-field full">Destination<input required name="destination" placeholder="e.g. Central Bus Station" value="${esc(state.journey?.destination||'')}"></label><label class="form-field">Transport<select name="transport"><option>Auto / Cab</option><option>Bus</option><option>Train</option><option>Walking</option><option>Other</option></select></label><label class="form-field">Vehicle number <input name="vehicle" placeholder="Optional"></label><label class="form-field full">Route or area details <input name="route" placeholder="Optional — e.g. via village junction"></label><div class="form-field full"><button class="primary" type="submit">Start journey & open navigation →</button><span style="font-size:12px;color:var(--muted);font-weight:400">Google Maps will open in a new tab using your destination.</span></div></form></div></section>`}
function contacts(){let saved=state.journey?.contacts||[];let rows=Array.from({length:5},(_,i)=>`<div class="contact-row"><input name="name${i}" placeholder="Contact name" value="${esc(saved[i]?.name||'')}"><input name="phone${i}" type="tel" placeholder="Mobile number" value="${esc(saved[i]?.phone||'')}"></div>`).join('');return `<section class="screen">${header('Trusted contacts','People who can stay informed','Add up to five contacts. They are stored only in this browser for the prototype.')}<div class="panel"><p class="step">STEP 2 OF 3 · TRUSTED CONTACTS</p><form id="contacts-form"><div class="contacts">${rows}</div><button class="primary">Submit contacts →</button></form></div></section>`}
function message(){let j=state.journey;return `<section class="screen">${header('Safety message','Add anything important','This creates a message you can copy or share with your contacts using your device’s supported options.')}<div class="panel"><p class="step">STEP 3 OF 3 · SAFETY MESSAGE</p><label class="form-field">Additional information<textarea id="custom-message" placeholder="e.g. I changed my auto near the village junction.">${esc(j.message||'')}</textarea></label><div class="location-box">⌖ Latest available location: <strong>${esc(state.location)}</strong> <button class="secondary" style="padding:6px 9px;margin-left:5px" id="loc-btn">Update</button></div><div class="button-row"><button class="primary" id="share-message">Generate & share safety message</button><button class="secondary" id="go-active">Continue to active journey</button></div><div class="future">Current prototype: prepares a message and opens your device’s share/copy options where supported. It does not automatically send SMS or WhatsApp messages.</div></div></section>`}
function active(){let j=state.journey;if(!j)return safety();return `<section class="screen">${header('Active journey','You’re on your way','Keep this page open to update your available location and access help quickly.')}<div class="journey-summary"><p class="eyebrow">● Journey in progress</p><h2>${esc(j.destination)}</h2><div class="journey-details"><div><span>TRANSPORT</span>${esc(j.transport)}</div><div><span>VEHICLE</span>${esc(j.vehicle||'Not added')}</div><div><span>CONTACTS</span>${j.contacts?.filter(x=>x.name).length||0} saved</div></div></div><div class="location-box">⌖ Latest available location: <strong>${esc(state.location)}</strong></div><div class="active-actions"><button data-go="help"><span>!</span>Help now</button><button id="navigate"><span>↗</span>Navigate</button><button id="update-location"><span>⌖</span>Update location</button><button id="safe"><span>✓</span>I am safe</button></div><div class="panel active-message"><p class="eyebrow">Safety message</p><h2>Keep your contacts informed</h2><p>Update your message whenever your plans change, then share the prepared alert through your device.</p><div class="button-row"><button class="primary" id="active-share">Share alert message</button><button class="secondary" id="edit-info">Update info</button></div><div id="update-info-box" class="update-info-box" hidden><label class="form-field">Updated information for trusted contacts<textarea id="active-message" placeholder="e.g. I changed my route and will arrive later.">${esc(j.message||'')}</textarea></label><div class="button-row"><button class="primary" id="save-info">Save updated info</button><button class="secondary" id="cancel-info">Cancel</button></div></div></div><div class="future">Current prototype: the alert can be copied or opened in your device’s share options. It does not automatically send messages to contacts.</div></section>`}
function help(){let sel=Object.keys(data.incidents).map(x=>`<button class="choice ${state.incident===x?'selected':''}" data-incident="${x}">${x}</button>`).join('');let guidance=state.incident?`<div class="panel incident-info"><p class="eyebrow">Immediate actions</p><h2>${esc(state.incident)}</h2><ul class="precautions">${data.incidents[state.incident].map(x=>`<li>${x}</li>`).join('')}</ul><div class="location-box">⌖ Latest available location: <strong>${esc(state.location)}</strong></div><div class="button-row"><a class="danger" href="tel:112" style="text-decoration:none">Call 112 emergency</a><button class="secondary" id="help-share">Copy safety alert</button></div></div>`:'';return `<section class="screen">${header('Immediate support','I need help now','Choose what is happening for clear next steps. If you are in immediate danger, call 112.')}<div class="help-banner"><h2>Emergency in India?</h2><div>Call 112 for immediate emergency assistance. SafeSphere cannot contact emergency services automatically.</div><div class="button-row" style="margin-top:14px"><a class="danger" href="tel:112" style="text-decoration:none">Call 112 now</a><button class="secondary" id="contact-authorities">Contact police & authorities</button></div></div><div class="choice-grid">${sel}</div>${guidance}<div class="modal-backdrop" id="authority-modal" hidden><div class="modal" role="dialog" aria-modal="true" aria-labelledby="authority-title"><button class="modal-close" id="close-authority-modal" aria-label="Close popup">×</button><p class="eyebrow">Future development</p><h2 id="authority-title">Contact police & authorities</h2><p>In a production version, SafeSphere could send an authorized emergency alert with the latest available location to relevant police stations and traffic authorities.</p><ul class="precautions"><li>Nearby police-station alerting would need official authorization and a secure backend.</li><li>Traffic police or other authority alerts would need approved service integration.</li><li>The current prototype prepares a safety alert and gives quick access to emergency calling.</li></ul><div class="button-row"><a class="danger" href="tel:112" style="text-decoration:none">Call 112 now</a><button class="secondary" id="close-authority-modal-2">Close</button></div></div></div></section>`}
function reports(){return `<section class="screen">${header('Reporting','Prepare, don’t rush','Learn what may help, then prepare a clear report summary for the appropriate reporting pathway.')}<div class="report-tabs"><button class="report-tab active" data-report="rights">Know my rights</button><button class="report-tab" data-report="evidence">What evidence is needed?</button><button class="report-tab" data-report="submit">Prepare report</button></div><div id="report-content">${reportContent('rights')}</div></section>`}
function reportContent(tab){if(tab==='rights')return `<div class="info-grid"><div class="info-card"><h3>Prioritize immediate safety</h3><p>If there is an immediate danger, move to a safer public place and call 112. Ask a trusted person for support if you can.</p></div><div class="info-card"><h3>Seek appropriate help</h3><p>You may contact local emergency services, police, a cybercrime reporting pathway, or a trusted support organization based on the situation.</p></div><div class="info-card"><h3>Keep a clear record</h3><p>Write down what happened while it is fresh. Preserve relevant information without putting yourself at risk.</p></div></div><div class="future">General information only—not legal advice. Requirements and reporting pathways can vary by situation and location.</div>`;if(tab==='evidence')return `<div class="panel"><h2>Useful records to preserve</h2><p style="color:var(--muted);line-height:1.55">These records may help authorities understand or investigate an incident. What is required can vary by situation.</p><div class="checklist">${['Screenshots or messages','Existing photos or videos','Date and time','Location details','Vehicle number','Witness information','Account or profile details','Relevant URLs or links'].map(x=>`<div class="check">✓ ${x}</div>`).join('')}</div></div>`;return `<div class="panel"><form id="report-form" class="form-grid"><label class="form-field">Incident type<select name="type"><option>Harassment</option><option>Unsafe travel</option><option>Online harassment</option><option>Threat / intimidation</option><option>Other</option></select></label><label class="form-field">Date<input name="date" type="date"></label><label class="form-field full">Location or online platform<input name="location" placeholder="Where did it happen?"></label><label class="form-field full">Person, vehicle, or account details<input name="details" placeholder="Optional"></label><label class="form-field full">What happened?<textarea name="description" required placeholder="Describe the incident clearly and factually."></textarea></label><div class="form-field full"><span>Evidence you have</span><div class="checklist">${['Screenshots','Messages/chats','Photos/videos','Date/time','Location','Vehicle/account details'].map(x=>`<label class="check"><input type="checkbox" name="evidence" value="${x}">${x}</label>`).join('')}</div><button class="primary">Save & prepare report</button></div></form></div>`}
function online(){let choices=Object.keys(data.online).map(x=>`<button class="choice ${state.online===x?'selected':''}" data-online="${x}">${x}</button>`).join('');let d=state.online?`<div class="panel incident-info"><p class="eyebrow">Digital safety steps</p><h2>${esc(state.online)}</h2><ul class="precautions">${data.online[state.online].map(x=>`<li>${x}</li>`).join('')}</ul><h3>Useful evidence</h3><div class="checklist">${['Screenshots','Messages/chats','Username or profile','Relevant URL','Date/time','Existing media/files'].map(x=>`<div class="check">✓ ${x}</div>`).join('')}</div><button class="primary" data-go="reports">Prepare a report →</button><div class="future">SafeSphere helps you prepare information. Automatic platform reporting and secure evidence uploads are future-development features.</div></div>`:'';return `<section class="screen">${header('Digital safety','Online harassment','Choose the problem to see calm, practical steps and evidence guidance.')}<div class="choice-grid">${choices}</div>${d}</section>`}
function render(){let pages={home,safety,setup,contacts,message,active,help,reports,online};$('#app').innerHTML=pages[state.screen]();nav();bind();}
function updateLocation(){if(!navigator.geolocation){toast('Location is not supported by this browser.');return}toast('Requesting your location…');navigator.geolocation.getCurrentPosition(p=>{state.location=`${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`;localStorage.setItem('ssLocation',state.location);toast('Location updated.');render()},()=>toast('Location permission was not granted. You can continue without it.'),{enableHighAccuracy:true,timeout:9000});}
function safetyText(){let j=state.journey||{};return `SAFESPHERE SAFETY ALERT\n\nDestination: ${j.destination||'Not added'}\nTransport: ${j.transport||'Not added'}\nVehicle Number: ${j.vehicle||'Not added'}\n\nAdditional Information:\n${j.message||'No additional information'}\n\nLatest Available Location:\n${state.location}`}
async function share(){let text=safetyText();try{if(navigator.share){await navigator.share({title:'SafeSphere Safety Alert',text});toast('Safety alert opened in your share options.')}else{await navigator.clipboard.writeText(text);toast('Safety alert copied to your clipboard.')}}catch(e){if(e.name!=='AbortError')toast('Could not share automatically. You can copy the message from this screen.')}}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('[data-situation]').forEach(b=>b.onclick=()=>{state.situation=b.dataset.situation;render();setTimeout(()=>$('#precautions')?.scrollIntoView({behavior:'smooth'}),50)});document.querySelectorAll('[data-incident]').forEach(b=>b.onclick=()=>{state.incident=b.dataset.incident;render()});document.querySelectorAll('[data-online]').forEach(b=>b.onclick=()=>{state.online=b.dataset.online;render()});$('#journey-form')?.addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target);state.journey={destination:f.get('destination'),transport:f.get('transport'),vehicle:f.get('vehicle'),route:f.get('route'),contacts:[]};save();window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(state.journey.destination)}`,'_blank','noopener');toast('Google Maps opened. Continue adding trusted contacts here.');go('contacts')});$('#contacts-form')?.addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target);state.journey.contacts=Array.from({length:5},(_,i)=>({name:f.get('name'+i),phone:f.get('phone'+i)})).filter(x=>x.name||x.phone);save();go('message')});$('#loc-btn')?.addEventListener('click',updateLocation);$('#share-message')?.addEventListener('click',()=>{state.journey.message=$('#custom-message').value.trim();save();share()});$('#go-active')?.addEventListener('click',()=>{state.journey.message=$('#custom-message').value.trim();save();go('active')});$('#navigate')?.addEventListener('click',()=>window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(state.journey.destination)}`,'_blank','noopener'));$('#update-location')?.addEventListener('click',updateLocation);$('#safe')?.addEventListener('click',()=>{localStorage.removeItem('ssJourney');state.journey=null;toast('Journey completed successfully. Take care.');go('home')});$('#help-share')?.addEventListener('click',share);$('#contact-authorities')?.addEventListener('click',()=>{$('#authority-modal').hidden=false});document.querySelectorAll('#close-authority-modal, #close-authority-modal-2').forEach(button=>button.addEventListener('click',()=>{$('#authority-modal').hidden=true}));document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-report]').forEach(x=>x.classList.toggle('active',x===b));$('#report-content').innerHTML=reportContent(b.dataset.report);bind()});$('#report-form')?.addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target);let report={type:f.get('type'),date:f.get('date'),location:f.get('location'),details:f.get('details'),description:f.get('description'),evidence:f.getAll('evidence')};localStorage.setItem('ssReport',JSON.stringify(report));toast('Report summary saved on this browser. It was not submitted to authorities.');})}
document.addEventListener('click', event => {
  const id = event.target.closest('button')?.id;
  if (id === 'active-share') share();
  if (id === 'edit-info') {
    $('#update-info-box').hidden = false;
    $('#active-message').focus();
  }
  if (id === 'cancel-info') $('#update-info-box').hidden = true;
  if (id === 'save-info') {
    state.journey.message = $('#active-message').value.trim();
    save();
    $('#update-info-box').hidden = true;
    toast('Your updated information is ready to share.');
  }
});
render();


